DROP TABLE IF EXISTS contas;

CREATE TABLE contas (
    id IDENTITY PRIMARY KEY,
    nome VARCHAR(250) NOT NULL,
    tipo ENUM('PAGAR', 'RECEBER') NOT NULL DEFAULT 'PAGAR',
    ciclo ENUM('PERMANENTE', 'PARCELADA') NOT NULL DEFAULT 'PERMANENTE',
    parcelas INT NOT NULL DEFAULT 1,
    valor NUMERIC(18,2) NOT NULL DEFAULT 0.0,
    data_criacao DATE NOT NULL
);

INSERT INTO contas(id, nome, tipo, ciclo, parcelas, valor, data_criacao) VALUES
    (100, 'Joao', 'RECEBER', 'PERMANENTE', 1, 503.56, CURRENT_DATE),
    (101, 'Maria', 'PAGAR', 'PERMANENTE', 1, 102.30, CURRENT_DATE),
    (102, 'Josefina', 'RECEBER', 'PARCELADA', 4, 10000.00, CURRENT_DATE);